---
lanInterface: ens192
lanIP: 192.168.0.1
lanNet: 192.168.0.0/16

wanIP: 95.216.39.156

zones:
  - zone: replicas.lan
    zoneIP: "{{ lanIP }}"
    zoneAdmin: rhh\.klussmann.gmail.com
    allowQueries: 192.168.0.0/16; 127.0.0.1;
    allowTransfer: none;
    renewKeys: false
    nsRecords:
      - record: ns1
        value: replicas.lan
    # mxRecords:
    #   - record: mx
    #     value: "{{ lanIP }}"
    aRecords:
      - record: gw
        value: "{{ lanIP }}"

      - record: ns1
        value: "{{ lanIP }}"

      - record: master0
        value: 192.168.0.10

      - record: gluster-node0
        value: 192.168.0.20

      - record: gluster-node1
        value: 192.168.0.21

      - record: gluster-node2
        value: 192.168.0.22

      - record: gluster-node3
        value: 192.168.0.23

      - record: gluster-node4
        value: 192.168.0.24

      - record: gluster-node5
        value: 192.168.0.25

      - record: infra-node0
        value: 192.168.0.30

      - record: comp-node0
        value: 192.168.0.40

      - record: build-node0
        value: 192.168.0.60


  - zone: replicas.io
    zoneIP: "{{ wanIP }}"
    zoneAdmin: rhh\.klussmann.gmail.com
    nsSub: ns1
    nsIP: "{{ wanIP }}"
    allowQueries: any;
    allowTransfer: 173.244.206.26; 88.198.106.11; 108.61.224.67; 116.203.6.3; 107.191.99.111; 185.22.172.112; 103.6.87.125; 192.184.93.99; 119.252.20.56; 107.181.178.180; 185.34.136.178; 185.136.176.247; 45.77.29.133; 116.203.0.64; 167.88.161.228; 199.195.249.208; 104.244.78.122; 2605:6400:30:fd6e::3; 2605:6400:10:65::3; 2605:6400:20:d5e::3; 2a01:4f8:1c1c:8185::3; 2001:19f0:7001:381::3; 2a06:fdc0:fade:2f7::1; 2a00:dcc7:d3ff:88b2::1; 2607:f7a0:a:23::3; 2401:1400:1:1201::1:7853:1a5; 2604:180:1:92a::3; 2403:2500:4000::f3e; 2a00:1838:20:2::cd5e:68e9; 2604:180:2:4cf::3; 2a01:4f8:1c0c:8115::3; 2001:19f0:6400:8642::3;
    renewKeys: false
    nsRecords:
      - record: ns1
        value: replicas.io
        # Germany, EU
      - record: uz5x36jqv06q5yulzwcblfzcrk1b479xdttdm1nrgfglzs57bmctl8.free.ns
        value: buddyns.com
        # Netherlands, Europe
      - record: uz56xw8h7fw656bpfv84pctjbl9rbzbqrw4rpzdhtvzyltpjdmx0zq.free.ns
        value: buddyns.com
        # USA, New York
      - record: uz588h0rhwuu3cc03gm9uckw0w42cqr459wn1nxrbzhym2wd81zydb.free.ns
        value: buddyns.com
        # USA, Seattle
      - record: uz5dkwpjfvfwb9rh1qj93mtup0gw65s6j7vqqumch0r9gzlu8qxx39.free.ns
        value: buddyns.com
        # Australia, Adelaide
      - record: uz5w6sb91zt99b73bznfkvtd0j1snxby06gg4hr0p8uum27n0hf6cd.free.ns
        value: buddyns.com
        # USA, California
      - record: uz5qfm8n244kn4qz8mh437w9kzvpudduwyldp5361v9n0vh8sx5ucu.free.ns
        value: buddyns.com
        # Romania, Europe
      - record: uz5x6wcwzfbjs8fkmkuchydn9339lf7xbxdmnp038cmyjlgg9sprr2.free.ns
        value: buddyns.com
        # USA, Texas
      - record: uz53c7fwlc89h7jrbxcsnxfwjw8k6jtg56l4yvhm6p2xf496c0xl40.free.ns
        value: buddyns.com
        # St. Petersburg, Russia
      - record: uz5c15kc3lkws2mtwp7l8g9f33yffvvt96y54tlmn41zjy0043purm.free.ns
        value: buddyns.com
        # Tokyo, Japan
      - record: uz52u1wtmumlrx5fwu6nmv22ntcddxcjjw41z8sfd6ur9n7797lrv9.free.ns
        value: buddyns.com
        # Asia, India
      - record: uz5154v9zl2nswf05td8yzgtd0jl6mvvjp98ut07ln0ydp2bqh1skn.free.ns
        value: buddyns.com
    # mxRecords:
    #   - record: mx
    #     value: "{{ lanIP }}"
    txtRecords:
      - record: '_acme-challenge'
        value: 'ELU8asbvXEFc4kL8XxJPc_mOq0EgDWrpnwFGAIls5k0'
    aRecords:
      - record: ns1
        value: "{{ wanIP }}"
    subDomains:
      - name: infra
        zone: replicas.io
        records:
          - record: ocp
            value: "{{ wanIP }}"
